### ISSUE TITLE
Time management

### ISSUE THREAD

**Issue by mbootsector** [official-stockfish/Stockfish#510]
Time management needs to be rewritten or simplified, and there also seems to be a bug with pondering.

The Ponder UCI option defaults to true, and AFAIK fishtest doesn't send ponder=off when running tests, and in Timemanager.cpp we have this:
if (Options["Ponder"])
  optimumTime += optimumTime / 4;
Seems SF always uses 25% more time than originally intended.

Further, in TimeManager.h we have:
int available() const { return int(optimumTime * unstablePvFactor * 0.76); }

Currently we first add 25% time, and later remove 24%.

**Comment by zamar** [comment]
Here we are mixing and matching completely unrelated issues:

1) You claim that cutechess-cli doesn't send Ponder=Off to engine. If this indeed is the case, then we need to raise a high-priority bug against cutechess-cli. Can you please verify that this is the case? Just run SF in debug mode under cutechess.

2) Using more time when pondering is on.
if (Options["Ponder"])
    optimumTime += optimumTime / 4;

There is no bug here, this is the intended behaviour.

3) Using factor 0.76 in available()
int available() const { return int(optimumTime * unstablePvFactor * 0.76); }

There is no bug here, this is the intended behaviour.

4) About simplifying or rewriting time management... Whenever somebody comes up with the solution that is simpler or stronger than the current code, it will be committed. The same applies to everything else in SF.

**Comment by lp--** [comment]
@zamar: I did check that local cutechess-cli does not send  ponder off when starting new game some time ago. Not sure  if cutechess-cli in fishtest  also does not send it (I assume so) or  what other GUIs do.

But I think currently there is bug in stockfish. Time management was tuned in fishtest when uci option "Ponder" was on by default.  If GUI send ponder off then optimum time will get adjusted 25% downward. This should be fixed.

I think by default it is better to keep uci option ponder as "off" and have the same behavior independently if ponder off is sent or not. 

Functionally equivalent change doing that is here:
https://github.com/lp--/Stockfish/compare/lp--:5d077bb...c56b9e1

I left time for ponder on unadjusted as this is how much time stockfish gets currently in ponder on games. It is not optimal behaviour, and should be tuned in fishtest when ponder on  testing will become possible. Another alternative is to leave additional time at 25% (or another percentage) more for ponder on games   without testing.

**Comment by lp--** [comment]
I should add that I tried to test nicer form of bug  fix without intoducing additional factor, but test did not pass

**Comment by Matt14916** [comment]
I've seen people mention before that time management was tuned on fishtest, but most of the parameters are unchanged from the original round of simplifications from around 2 years ago. Slow mover, best move changes, and the multiplication factor in available() have changed, but the core move importance stuff is still the same.

**Comment by zamar** [comment]
What about...
- Change the default value of "Ponder" to false.
- Retune the time management (especially "Slow Mover").

For me that would sound like the most sensible thing to do...

**Comment by lp--** [comment]
@zamar: Yes, retuning parameters with ponder set to false would be preferable,   if it can be done without elo loss.

**Comment by mbootsector** [comment]
@zamar I tested by changing SF code to something like:
if (Options["Ponder"]) {
  optimumTime += optimumTime / 4;
  printf("ponder is on\n");
}
and ran cutechess in debug mode, and the logs showed that "ponder is on" was sent from SF. I tested with cutechess from the command line, haven't tested with fishtest, I assume the same problem exists there.
About 2) and 3). My point was that they only work as intended if 1) is working.
